if(NOT IS_DIRECTORY "${SOURCE_DIR}")
    message(FATAL_ERROR "Runtime data directory does not exist: ${SOURCE_DIR}")
endif()
file(GLOB_RECURSE runtime_files LIST_DIRECTORIES false "${SOURCE_DIR}/*")
foreach(source_file IN LISTS runtime_files)
    get_filename_component(extension "${source_file}" EXT)
    string(TOLOWER "${extension}" extension_lower)
    if(extension_lower STREQUAL ".exe" OR extension_lower STREQUAL ".dll" OR extension_lower STREQUAL ".pdb" OR extension_lower STREQUAL ".obj")
        continue()
    endif()
    file(RELATIVE_PATH relative_path "${SOURCE_DIR}" "${source_file}")
    get_filename_component(relative_dir "${relative_path}" DIRECTORY)
    if(relative_dir STREQUAL "")
        set(destination_dir "${DEST_DIR}")
    else()
        set(destination_dir "${DEST_DIR}/${relative_dir}")
    endif()
    file(MAKE_DIRECTORY "${destination_dir}")
    file(COPY "${source_file}" DESTINATION "${destination_dir}")
endforeach()
